sudo: required

services:
  - docker

cache:
  timeout: 600
  bundler: false
  directories:
  - $HOME/.stack
  #- /var/lib/docker
  - $HOME/docker  #https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
  - $HOME/build/peterbecich/stock-servant/.stack-work

  
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

  - eval "$(ssh-agent -s)" #start the ssh agent

  - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_secrets.tar.enc -out travis_servant_secrets.tar -d
  - tar xvf travis_servant_secrets.tar

  - chmod 600 travis_servant
  - ssh-add travis_servant
  
  - chmod 600 travis_servant_stats
  - ssh-add travis_servant_stats

  - chmod 600 travis_servant_common
  - ssh-add travis_servant_common

  - chmod 600 travis_servant_stats_common
  - ssh-add travis_servant_stats_common

  - chmod 600 travis_servant_push_github
  - ssh-add travis_servant_push_github
  
  - git submodule update --init --recursive

  - docker pull fpco/stack-build:lts-9.17

  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup
  
script:
  - echo "foobar"
  # - stack build
  # - stack image container
  
addons:
  ssh_known_hosts:

  
# https://docs.travis-ci.com/user/deployment/custom/
#after_success:
  # - eval "$(ssh-agent -s)" #start the ssh agent
  # - chmod 600 scaleway_travis_servant # this key should have push access
  # - ssh-add scaleway_travis_servant
  # - git config --global receive.denyCurrentBranch ignore
  # - git remote add deploy git@ce3b12e3-5fee-4248-b3e4-24dfc4fc38c6.pub.cloud.scaleway.com:/srv/stock-servant/.git
  # - git push deploy master

after_success:
  # - echo "success; run merge_script.sh"
  # - ./scripts/merge_script.sh

git:
  submodules: false

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
  
