sudo: required

services:
  - docker

# Caching so the next build will be fast too.
cache:
  timeout: 600
  directories:
  - $HOME/.stack
  - /var/lib/docker

before_install:
  - eval "$(ssh-agent -s)" #start the ssh agent

  # - openssl aes-256-cbc -K $encrypted_67f787260264_key -iv $encrypted_67f787260264_iv -in scaleway_travis_servant.enc -out scaleway_travis_servant -d

  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_stats.enc -out travis_servant_stats -d
  # - chmod 600 travis_servant_stats
  # - ssh-add travis_servant_stats

  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_common2.enc -out travis_servant_common2 -d
  # - chmod 600 travis_servant_common2
  # - ssh-add travis_servant_common2

  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_stats2.enc -out travis_servant_stats2 -d
  # - chmod 600 travis_servant_stats2
  # - ssh-add travis_servant_stats2
  
  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_common.enc -out travis_servant_common -d
  # - chmod 600 travis_servant_common
  # - ssh-add travis_servant_common

  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_stats3.enc -out travis_servant_stats3 -d
  # - chmod 600 travis_servant_stats3
  # - ssh-add travis_servant_stats3

  - openssl aes-256-cbc -k "$servant_common_pass" -in travis_servant_common2.enc -out travis_servant_common2 -d
  - chmod 600 travis_servant_common2
  - ssh-add travis_servant_common2

  - openssl aes-256-cbc -k "$servant_stats_pass" -in travis_servant_stats3.enc -out travis_servant_stats3 -d
  - chmod 600 travis_servant_stats3
  - ssh-add travis_servant_stats3

  
  
  - git submodule update --init --recursive

  - docker pull fpco/stack-build:lts-9.17
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup

script:
  - stack build

addons:
  ssh_known_hosts:

  
# https://docs.travis-ci.com/user/deployment/custom/
after_success:
  # - eval "$(ssh-agent -s)" #start the ssh agent
  # - chmod 600 scaleway_travis_servant # this key should have push access
  # - ssh-add scaleway_travis_servant
  # - git config --global receive.denyCurrentBranch ignore
  # - git remote add deploy git@ce3b12e3-5fee-4248-b3e4-24dfc4fc38c6.pub.cloud.scaleway.com:/srv/stock-servant/.git
  # - git push deploy master
  
git:
  submodules: false


secure:
  - "oj8V6tsJEkR1AyuhZkvA/rXw7r2e4pX7gPSAujvrjvceG2y0IbdIxMHoInb8DxPJsqlICdTshniJ48bdy3QXXrNQHFISGLOFvpHtDR9tauYFJZ/kmWVtm+X2kkcaD/2QF3lWq8Gx+I5XP4hcSkogvqKftyxojJEsAgAiRgffcpWzyWIflP2q+44W/O84EofIJBGjki8pUCTFpWu7CCbPXVvKzo9jmjgu46E/tT617tv2mwvsJtU/hGr5u7hmUai7cT1Ollir5BgyEo+nZ9UBNkImsHCzHcAAp+nhPn+NQLtknTfu1xdSq5zgei9xueXgKonythDM6r6ki2x3KKKFWGNZ0pOI5C6/uwiGfFokMTQg6GtnmmuPcFbpIOOrEK5z9PMeBlxMINm/BEEFKnzVuNVIgDaSbo99svfrQyzK/tOLm2GO7MMTda+g4DH7JiN8ONzvfETksP2NQvaqTtpJ4zWXZurCTBLwCOupxC1CV0loJxWE9Z6WVswJGzH0iibY5KEgF6D1gTxVra9arNkanrLdeOA/nd9f0DLp1yw8sNMopAZqZlqkOPCJ/6Yo+VtAfxg/NefR+2ZxpM2DEZKkBLpxJ1fxnr7bduoyhms3PJ3ybfkfCGbVogQ1+Yy035dNxBWG4EBDA9zPfpHWQpWqOfBIWLfVvSRvTPomSPzNWN8="
  
  - "siogJD6P4mB+7DBK+GVHddk1YcaoZ+3VuPKaeQvzcAhXYO6mM/lyGgDmgNw19FWPVDcW+IlDIGLb3gnnsnL2g/pZLwZiM0BhgXWIdma23wx/snDFY3ZzmGbiV5ejoRXcYi3hANCWOvqqDxjFhRGCaUopm1UHabIAbgcVlve3qTL7nwZY6RXpwSoXyD70PrFj7cY8kwQwZ4xKQ80YukQ5Drtp3qH+wZsWArHqqZm96qblBp2cT1duzORSC5lX99WAtVBbBIp6w6pme7W4dTU0Fh824M/TEIlf8VlvDdj+TEOV0tuqb6ejUDTq2L+Gi8C7nGrqxF+WvM0i7K78brVGGCffUumqlH/etpV05X/GTrPuG6t4Zx3yiRXDotIszZFsp06G+J7EqNOza/w2Rue711CwM5N+W04RGCYnm93+veZobutIo+0RQyjqQGz+bxytUGHGTLu38+w8vj1EwFmzCr/VMTV63ttNeHn4+e4zNqlPxky7vtDBw5YwcJVb44igecJw0/sFwIrgpv8jNJV5GMB1otqPXJDNYTo0fA8ZSlzLnkhJmXiKf/uCuULUlTBlI1e4VLjJelgTFIaPOWq3gHz/GQ5+WE4r2cRFLcJxJWhCcuDkJvrsRjKuA3bev+Y02V2NhG0tQYI5VQPGyn4CG+3i6PBWrAo1dqbX0Pvl1mI="
