sudo: required

services:
  - docker

# Caching so the next build will be fast too.
cache:
  timeout: 600
  directories:
  - $HOME/.stack
  - /var/lib/docker

before_install:
  - eval "$(ssh-agent -s)" #start the ssh agent

  # - openssl aes-256-cbc -K $encrypted_67f787260264_key -iv $encrypted_67f787260264_iv -in scaleway_travis_servant.enc -out scaleway_travis_servant -d

  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_stats.enc -out travis_servant_stats -d
  # - chmod 600 travis_servant_stats
  # - ssh-add travis_servant_stats

  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_common2.enc -out travis_servant_common2 -d
  # - chmod 600 travis_servant_common2
  # - ssh-add travis_servant_common2

  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_stats2.enc -out travis_servant_stats2 -d
  # - chmod 600 travis_servant_stats2
  # - ssh-add travis_servant_stats2
  
  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_common.enc -out travis_servant_common -d
  # - chmod 600 travis_servant_common
  # - ssh-add travis_servant_common

  # - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_stats3.enc -out travis_servant_stats3 -d
  # - chmod 600 travis_servant_stats3
  # - ssh-add travis_servant_stats3

  - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_common2.enc -out travis_servant_common2 -d
  - chmod 600 travis_servant_common2
  - ssh-add travis_servant_common2

  - openssl aes-256-cbc -K $encrypted_1ea99ed25c80_key -iv $encrypted_1ea99ed25c80_iv -in travis_servant_stats3.enc -out travis_servant_stats3 -d
  - chmod 600 travis_servant_stats3
  - ssh-add travis_servant_stats3

  
  
  - git submodule update --init --recursive

  - docker pull fpco/stack-build:lts-9.17
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup

script:
  - stack build

addons:
  ssh_known_hosts:

  
# https://docs.travis-ci.com/user/deployment/custom/
after_success:
  # - eval "$(ssh-agent -s)" #start the ssh agent
  # - chmod 600 scaleway_travis_servant # this key should have push access
  # - ssh-add scaleway_travis_servant
  # - git config --global receive.denyCurrentBranch ignore
  # - git remote add deploy git@ce3b12e3-5fee-4248-b3e4-24dfc4fc38c6.pub.cloud.scaleway.com:/srv/stock-servant/.git
  # - git push deploy master
  
git:
  submodules: false
