version: '3'
services:
    stock-servant:
        build: .
        image: stock-servant
        command: stock-servant
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - stock-servant
