
resolver: lts-9.17

# https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md
packages:
- .
- stock-common
- stock-stats
extra-dep: true

extra-deps: [yaml-config-0.4.0, stock-common-0.1.0.0, stock-stats-0.1.0.0]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []


ghc-options:
  "*": -j -threaded

docker:
  enable: true
  
image:
  containers:
    -
      base: "fpco/stack-build:lts-9.17"
      name: "peterbecich/stock-servant"

      add:
        conf/: /usr/local/etc/

      entrypoints:
        - stock-servant
        - stock-servant-local

      executables:
        - stock-servant
        - stock-servant-local
