
resolver: lts-10.3

# https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md
packages:
- .
- stock-common
- stock-stats
extra-dep: true

extra-deps:
- yaml-config-0.4.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []


# ghc-options:
#   "*": -j -threaded

docker:
  enable: true
  
image:
  containers:
    -
      base: "fpco/stack-build:lts-10.3"
      name: "peterbecich/stock-servant"

      add:
        conf/: /usr/local/etc/
        stock-frontend/: /srv/stock-frontend/
        
      entrypoints:
        - stock-servant
        - stock-servant-local

      executables:
        - stock-servant
        - stock-servant-local
